name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'  # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  http: ^0.13.3
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  firebase_auth_web: ^5.8.13
  provider: ^6.0.3
  intl: ^0.20.2
  cached_network_image: ^3.2.3
  shared_preferences: ^2.4.0
  image_picker: ^0.8.4+5
  url_launcher: ^6.0.20
  upi_pay: ^1.1.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/pizza.jpg
    - assets/images/burger.jpg
    - assets/images/sushi.jpg
    - assets/images/desserts.jpg
    - assets/images/banner.jpg
    - assets/images/rest1.jpg
    - assets/images/rest2.jpg
    - assets/images/rest3.jpg
    - assets/images/rest4.jpg
    - assets/images/rest5.jpg
    - assets/images/rest6.jpg
    - assets/images/profile.jpg
    - assets/images/loginbackground.jpg
    - assets/images/applogo.jpg
    - assets/images/paneer.jpg
    - assets/images/salad.jpg
    - assets/images/pizza1.jpg
    - assets/images/pizza2.jpg
    - assets/images/burger1.jpg
    - assets/images/burger2.jpg
    - assets/images/dessert1.jpg
    - assets/images/dessert2.jpg
    - assets/images/logo.jpg
    - assets/images/default_avatar.jpg

